### ISSUE TITLE
A Way to change VPC/Network/Zone

### ISSUE THREAD

**Issue by bittix** [jcjorel/ec2-spot-converter#12]
Just a Suggestion, options to change vpc / network-id . We faced a problem where was not availability of a instance type in the current zone and we had to change network id changing zone

**Comment by jcjorel** [comment]
Hi,
Thanks for this suggestion. I had also colleagues that suggested the same recently for the same reasons than yours... It raises some specific challenges (Ip address change and EBS volume zonal affinity especially): I may create a tool dedicated for that purpose (EC2-instance-mover for instance) to move first as-is and convert after with existing ec2-spot-converter in the target subnet/VPC

**Comment by jcjorel** [comment]
I'm closing this issue as it won't be solved by modifying ec2-spot-converter but in another tool.
