### ISSUE TITLE
Tag Keys starting with aws: error with reserved word

### ISSUE THREAD

**Issue by kruule69** [jcjorel/ec2-spot-converter#13]
When instances are created with CloudFormation or Service Catalog, the services will create their own tags on instances.  These tags all start with "aws:".  When trying to convert, the error comes up that these are reserved tags.....

The tag keys maybe just renamed to something like changing "aws:cloudformation" to "AWScloudformation".

botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the RunInstances operation: Tag keys starting with 'aws:' are reserved for internal use

**Comment by jcjorel** [comment]
Hi,
Good catch! It is a side use-case as instances created with IaaC are less likely with the need to use EC2-spot-converter (It will create a configuration drift from a CloudFormation/TerraForm/Pulumi PoV) but it could useful in some case so will add the support. Thanks.

**Comment by kruule69** [comment]
Thanks for looking at adding this feature!  Kudos on this tool.... worked very well in our (small) test environment!

You are correct, this is probably not an issue for most but when deploying EC2 instances with CloudFormation stacks and AWS Service Catalog this is creating these tags.  To your point these instances should be built as spot to begin with, but for us it is not always the case (ie. lift-shift).

**Comment by jcjorel** [comment]
v0.14.0 released. Enjoy!

**Comment by jcjorel** [comment]
Jusr detected a small regession. v0.14.1 coming soon...

**Comment by jcjorel** [comment]
v0.14.1 released. Should be ok this time...
