### ISSUE TITLE
Copying tags for volumes when DeleteOnTermination is false

### ISSUE THREAD

**Issue by IvanNoronha-TomTom** [jcjorel/ec2-spot-converter#8]
While using the script for an on-demand to spot conversion I noticed the tags on original volume doesn't get copied to the new volume created.
In my case the DeleteOnTermination was originally false so there was an extra diff for volume,
![image](https://user-images.githubusercontent.com/73875852/109410873-22d70580-79c4-11eb-8168-d5e3301b3c20.png)

**Impact:**
I generally keep a backup schedule based on tags. Since the new volume won't have tag there's a requirement to manually add it, else the backup schedule will use the old volume. 
![image](https://user-images.githubusercontent.com/73875852/109410963-9547e580-79c4-11eb-943a-17dfc817f17b.png)

No biggie. But wanted to know your view

**Comment by jcjorel** [comment]
v0.11.0 released!
